google_project_id       = "fuchicorp-project-315576"
google_bucket_name      = "husne_mybucket"
deployment_environment  = "qa"
deployment_name         = "test-app"
credentials             = "fuchicorp-service-account.json"
